# Generated by Django 5.0.8 on 2024-09-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dog_name", models.CharField(max_length=200)),
                ("dog_boss", models.CharField(max_length=200)),
            ],
        ),
    ]
