version: '3'
services:
  db:
    image: mongo:latest
    container_name: lambda_mongo_db
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: password
        MONGO_INITDB_DATABASE: my_database
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - db_data:/data/db
    ports:
      - "27017:27017"

volumes:
  db_data:
