version: '3'
services:
  backend:
    image: sample_django_mysql_gunicorn
    build: 
      context: ./../../
      dockerfile: ./sample-apps/django-mysql-gunicorn/Dockerfile
    container_name: django_mysql_gunicorn_backend
    command: sh -c "python manage.py migrate && gunicorn -c gunicorn_config.py --workers 4 --threads 2 --log-level debug --access-logfile '-' --error-logfile '-' --bind 0.0.0.0:8000 sample-django-mysql-gunicorn-app.wsgi"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8082:8000"
    extra_hosts:
      - "app.local.aikido.io:host-gateway"
      - "host.docker.internal:host-gateway"
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      SECRET_KEY: 'abc'
      FIREWALL_DISABLED: 0


volumes:
  db_data:
