version: "3"
services:
  backend_firewall_disabled:
    image: sample_django_mysql_gunicorn
    command: sh -c "python manage.py migrate && ddtrace-run gunicorn -c gunicorn_config.py --workers 4 --threads 2 --log-level debug --access-logfile '-' --error-logfile '-' --bind 0.0.0.0:8000 sample-django-mysql-gunicorn-app.wsgi"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8083:8000"
    extra_hosts:
      - "app.local.aikido.io:host-gateway"
      - "host.docker.internal:host-gateway"
    environment:
      FIREWALL_DISABLED: 1
      SECRET_KEY: 'abc'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
  backend:
    env_file: .env.example

