version: '3'
services:
  backend:
    image: sample_flask_mysql
    build: 
      context: ./../../
      dockerfile: ./sample-apps/flask-mysql/Dockerfile
    container_name: flask_mysql_backend
    command: sh -c "flask --app app run --debug --host=0.0.0.0 --no-reload"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8086:5000"
    extra_hosts:
      - "app.local.aikido.io:host-gateway"
      - "host.docker.internal:host-gateway"
    environment:
      - FIREWALL_DISABLED=0
