version: '3'
services:
  backend:
    image: sample_flask_mssql
    build: 
      context: ./../../
      dockerfile: ./sample-apps/flask-mssql/Dockerfile
    container_name: flask_mssql_backend
    command: sh -c "flask --app app run --debug --host=0.0.0.0 --no-reload"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8104:5000"
    extra_hosts:
      - "app.local.aikido.io:host-gateway"
      - "host.docker.internal:host-gateway"
    environment:
      - FIREWALL_DISABLED=0
