version: '3'
services:

  backend:
    image: sample_flask_postgres
    build: 
      context: ./../../
      dockerfile: ./sample-apps/flask-postgres/Dockerfile
    container_name: flask_postgres_backend
    command: sh -c "flask --app app run --debug --host=0.0.0.0"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8090:5000"
    extra_hosts:
      - "app.local.aikido.io:host-gateway"
      - "host.docker.internal:host-gateway"
    environment:
      - FIREWALL_DISABLED=0
