version: '3'
services:
  db:
    image: postgres:14-alpine
    container_name: flask_postgres_db
    restart: always
    volumes:
      - db_data2:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      - default_network

  backend:
    build: 
      context: ./../../
      dockerfile: ./sample-apps/flask-postgres/Dockerfile
    container_name: flask_postgres_backend
    command: sh -c "flask --app app run --debug --host=0.0.0.0"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8080:5000"
    depends_on:
      - db
    networks:
      - default_network
    extra_hosts:
      - "app.local.aikido.io:host-gateway"


volumes:
  db_data2:

networks:
  default_network:
    driver: bridge
