version: "3"
services:
  backend_firewall_disabled:
    image: sample_fastapi_postgres_uvicorn
    command: sh -c "uvicorn app:app --host 0.0.0.0 --port 5000 --workers 4"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8105:5000"
    extra_hosts:
      - "app.local.aikido.io:host-gateway"
      - "host.docker.internal:host-gateway"
    environment:
      - FIREWALL_DISABLED=1
  backend:
    env_file: .env.example
