version: '3'
services:
  backend:
    image: sample_fastapi_postgres_uvicorn
    build: 
      context: ./../../
      dockerfile: ./sample-apps/fastapi-postgres-uvicorn/Dockerfile
    container_name: fastapi_postgres_uvicorn_backend
    command: sh -c "uvicorn app:app --host 0.0.0.0 --port 5000 --workers 4"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8104:5000"
    extra_hosts:
      - "app.local.aikido.io:host-gateway"
      - "host.docker.internal:host-gateway"
    environment:
      - FIREWALL_DISABLED=0
