version: "3"
services:
  backend_firewall_disabled:
    image: sample_django_postgres
    command: sh -c "python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8095:8000"
    extra_hosts:
      - "app.local.aikido.io:host-gateway"
      - "host.docker.internal:host-gateway"
    environment:
      FIREWALL_DISABLED: 1
      SECRET_KEY: 'Test key'
      DB_HOST: 'host.docker.internal'
      DB_NAME: 'db'
      DB_USER: 'user'
      DB_PASSWORD: 'password'
  backend:
    environment:
      AIKIDO_TOKEN: "test_aikido_token"
      AIKIDO_BLOCKING: 1

