version: '3'
services:
  backend:
    image: sample_django_postgres
    build: 
      context: ./../../
      dockerfile: ./sample-apps/django-postgres/Dockerfile
    container_name: django_postgres_backend
    command: sh -c "python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8094:8000"
    extra_hosts:
      - "app.local.aikido.io:host-gateway"
      - "host.docker.internal:host-gateway"
    environment:
      SECRET_KEY: 'Test key'
      DB_HOST: 'host.docker.internal'
      DB_NAME: 'db'
      DB_USER: 'user'
      DB_PASSWORD: 'password'
      FIREWALL_DISABLED: 0


volumes:
  db_data:
