version: '3'
services:
  backend:
    image: sample_flask_mongo
    build: 
      context: ./../../
      dockerfile: ./sample-apps/flask-mongo/Dockerfile
    container_name: flask_mongo_backend
    command: sh -c "ddtrace-run flask --app app run --debug --host=0.0.0.0"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8094:5000"
    extra_hosts:
      - "app.local.aikido.io:host-gateway"
      - "host.docker.internal:host-gateway"
    environment:
      FIREWALL_DISABLED: 0
