version: '3'
services:
  db:
    image: mongo:latest
    container_name: flask_mongo_db
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: password
        MONGO_INITDB_DATABASE: my_database
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - db_data:/data/db
    networks:
      - default_network



  backend:
    image: sample_flask_mongo
    build: 
      context: ./../../
      dockerfile: ./sample-apps/flask-mongo/Dockerfile
    container_name: flask_mongo_backend
    command: sh -c "flask --app app run --debug --host=0.0.0.0"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8084:5000"
    depends_on:
      - db
    networks:
      - default_network
    extra_hosts:
      - "app.local.aikido.io:host-gateway"
    environment:
      FIREWALL_DISABLED: 0

volumes:
  db_data:

networks:
  default_network:
    driver: bridge
