# docker-compose.prod.yml
version: "3"
services:
  backend_firewall_disabled:
    build: 
      context: ./../../
      dockerfile: ./sample-apps/django-mysql/Dockerfile
    command: sh -c "python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8081:8000"
    env_file:
      - .env
    depends_on:
      - db
    extra_hosts:
      - "app.local.aikido.io:host-gateway"
    environment:
      - FIREWALL_DISABLED=1
  backend:
    environment:
      - AIKIDO_TOKEN="test_aikido_token
