version: '3'
services:
  db:
    image: mysql
    container_name: django_mysql_mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

  backend:
    image: sample_django_mysql
    build: 
      context: ./../../
      dockerfile: ./sample-apps/django-mysql/Dockerfile
    container_name: django_mysql_backend
    command: sh -c "python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    depends_on:
      - db
    extra_hosts:
      - "app.local.aikido.io:host-gateway"
    environment:
      SECRET_KEY: 'Test key'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      FIREWALL_DISABLED: 0


volumes:
  db_data:
