version: '3'
services:
  backend:
    image: sample_flask_mysql_uwsgi
    build: 
      context: ./../../
      dockerfile: ./sample-apps/flask-mysql-uwsgi/Dockerfile
    container_name: flask_mysql_uwsgi_backend
    command: sh -c "uwsgi --ini uwsgi.ini"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8088:5000"
    extra_hosts:
      - "app.local.aikido.io:host-gateway"
      - "host.docker.internal:host-gateway"
    environment:
      - FIREWALL_DISABLED=0
