version: "3"
services:
  backend_firewall_disabled:
    image: sample_quart_mongo
    command: sh -c "QUART_APP=app:app quart run --host 0.0.0.0"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8099:5000"
    extra_hosts:
      - "app.local.aikido.io:host-gateway"
      - "host.docker.internal:host-gateway"
    environment:
      - FIREWALL_DISABLED=1
  backend:
    environment:
      - AIKIDO_TOKEN="test_aikido_token"
      - AIKIDO_BLOCKING=1

