name: End-to-End tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pip install poetry
      - name: Build
        run: make build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pkg-build
          path: ./

  end2end-test:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: build
    strategy:
      matrix:
        app:
          - { name: django-mysql, testfile: end2end/django_mysql.py }
          - { name: django-mysql-gunicorn, testfile: end2end/django_mysql_gunicorn.py }
          - { name: django-postgres-gunicorn, testfile: end2end/django_postgres_gunicorn.py }
          - { name: flask-mongo, testfile: end2end/flask_mongo.py }
          - { name: flask-mysql, testfile: end2end/flask_mysql.py }
          - { name: flask-mysql-uwsgi, testfile: end2end/flask_mysql_uwsgi.py }
          - { name: flask-postgres, testfile: end2end/flask_postgres.py }
          - { name: flask-postgres-xml, testfile: end2end/flask_postgres_xml.py }
          - { name: quart-postgres-uvicorn, testfile: end2end/quart_postgres_uvicorn.py }
          - { name: starlette-postgres-uvicorn, testfile: end2end/starlette_postgres_uvicorn.py }
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Install packages
        run: sudo apt update && sudo apt install python3-dev libmysqlclient-dev
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pkg-build

      - name: Start databases
        working-directory: ./sample-apps/databases
        run: docker compose up --build -d
      - name: Build and start aikido mock server
        run: |
            cd end2end/server && docker build -t mock_core .
            docker run --name mock_core -d -p 5000:5000 mock_core

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install

      - name: Start application
        working-directory: ./sample-apps/${{ matrix.app.name }}
        run: |
          nohup make run > output.log & tail -f output.log & sleep 20
          nohup make runZenDisabled & sleep 20
      - name: Run end2end tests for application
        run: tail -f  ./sample-apps/${{ matrix.app.name }}/output.log & python ./${{ matrix.app.testfile }}
