name: 🔥 Smoke Tests for FFI
on: [push]
permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-14 is ARM-based
        # macos-14-large is x86-based
        # ubuntu-latest (x86) is not included because the full test suite runs on it
        os: [windows-latest, macos-14, macos-14-large, ubuntu-22.04-arm]

    # Allows all jobs to run even if one fails
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.14

      - name: Display system info
        run: |
          python -c "import platform; print(f'Machine architecture: {platform.machine()}')"
          python -c "import platform; print(f'OS: {platform.system()}')"

      - name: Install MySQL
        if: runner.os == 'macOS'
        run: brew install mysql

      - name: Install MySQL
        if: runner.os == 'Linux'
        run: sudo apt-get install libmysqlclient-dev

      - name: Setup safe-chain (Unix)
        if: runner.os != 'Windows'
        run: curl -fsSL https://github.com/AikidoSec/safe-chain/releases/latest/download/install-safe-chain.sh | sh -s -- --ci
      - name: Setup safe-chain (Windows)
        if: runner.os == 'Windows'
        run: iex "& { $(iwr 'https://github.com/AikidoSec/safe-chain/releases/latest/download/install-safe-chain.ps1' -UseBasicParsing) } -ci"

      - name: Install dependencies
        run: make install && cp -r .cache/binaries/* aikido_zen/libs

      - name: Run tests
        run: poetry run pytest aikido_zen/vulnerabilities/sql_injection/init_test.py
